# Generated by Django 5.0.2 on 2024-03-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='image',
            field=models.ImageField(default='', upload_to='company_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
