# Generated by Django 5.0.2 on 2024-03-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_companyinformation_email_companyinformation_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedinuser',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50),
            preserve_default=False,
        ),
    ]
